[
  [
    {
      name: "United States Minor Outlying Islands",
      region: "Americas",
      population: 300,
      flags: {
        svg: "https://flagcdn.com/um.svg",
        png: "https://flagcdn.com/w320/um.png",
      },
      currencies: [{ code: "GBP", name: "British pound", symbol: "£" }],
      flag: "https://flagcdn.com/um.svg",
      independent: false,
    },
    {
      name: "Tanzania, United Republic of",
      topLevelDomain: [".tz"],
      alpha2Code: "TZ",
      alpha3Code: "TZA",
      callingCodes: ["255"],
      capital: "Dodoma",
      altSpellings: [
        "TZ",
        "United Republic of Tanzania",
        "Jamhuri ya Muungano wa Tanzania",
      ],
      subregion: "Eastern Africa",
      region: "Africa",
      population: 59734213,
      latlng: [-6.0, 35.0],
      demonym: "Tanzanian",
      area: 945087.0,
      gini: 40.5,
      timezones: ["UTC+03:00"],
      borders: ["BDI", "COD", "KEN", "MWI", "MOZ", "RWA", "UGA", "ZMB"],
      nativeName: "Tanzania",
      numericCode: "834",
      flags: {
        svg: "https://flagcdn.com/tz.svg",
        png: "https://flagcdn.com/w320/tz.png",
      },
      currencies: [{ code: "TZS", name: "Tanzanian shilling", symbol: "Sh" }],
      languages: [
        {
          iso639_1: "sw",
          iso639_2: "swa",
          name: "Swahili",
          nativeName: "Kiswahili",
        },
        {
          iso639_1: "en",
          iso639_2: "eng",
          name: "English",
          nativeName: "English",
        },
      ],
      translations: {
        br: "Tanzânia",
        pt: "Tanzânia",
        nl: "Tanzania",
        hr: "Tanzanija",
        fa: "تانزانیا",
        de: "Tansania",
        es: "Tanzania",
        fr: "Tanzanie",
        ja: "タンザニア",
        it: "Tanzania",
        hu: "Tanzánia",
      },
      flag: "https://flagcdn.com/tz.svg",
      regionalBlocs: [
        {
          acronym: "AU",
          name: "African Union",
          otherNames: [
            "الاتحاد الأفريقي",
            "Union africaine",
            "União Africana",
            "Unión Africana",
            "Umoja wa Afrika",
          ],
        },
      ],
      cioc: "TAN",
      independent: true,
    },
    {
      name: "United Arab Emirates",
      capital: "Abu Dhabi",
      region: "Asia",
      population: 9890400,
      flags: {
        svg: "https://flagcdn.com/ae.svg",
        png: "https://flagcdn.com/w320/ae.png",
      },
      currencies: [
        { code: "AED", name: "United Arab Emirates dirham", symbol: "د.إ" },
      ],
      flag: "https://flagcdn.com/ae.svg",
    },
    {
      name: "United Kingdom of Great Britain and Northern Ireland",
      capital: "London",
      region: "Europe",
      population: 67215293,
      flags: {
        svg: "https://flagcdn.com/gb.svg",
        png: "https://flagcdn.com/w320/gb.png",
      },
      currencies: [{ code: "GBP", name: "British pound", symbol: "£" }],
      flag: "https://flagcdn.com/gb.svg",
      cioc: "GBR",
      independent: true,
    },
    {
      name: "United States of America",
      topLevelDomain: [".us"],
      alpha2Code: "US",
      alpha3Code: "USA",
      callingCodes: ["1"],
      capital: "Washington, D.C.",
      altSpellings: ["US", "USA", "United States of America"],
      subregion: "Northern America",
      region: "Americas",
      population: 329484123,
      latlng: [38.0, -97.0],
      demonym: "American",
      area: 9629091.0,
      gini: 41.4,
      timezones: [
        "UTC-12:00",
        "UTC-11:00",
        "UTC-10:00",
        "UTC-09:00",
        "UTC-08:00",
        "UTC-07:00",
        "UTC-06:00",
        "UTC-05:00",
        "UTC-04:00",
        "UTC+10:00",
        "UTC+12:00",
      ],
      borders: ["CAN", "MEX"],
      nativeName: "United States",
      numericCode: "840",
      flags: {
        svg: "https://flagcdn.com/us.svg",
        png: "https://flagcdn.com/w320/us.png",
      },
      currencies: [{ code: "USD", name: "United States dollar", symbol: "$" }],
      languages: [
        {
          iso639_1: "en",
          iso639_2: "eng",
          name: "English",
          nativeName: "English",
        },
      ],
      translations: {
        br: "Estados Unidos",
        pt: "Estados Unidos",
        nl: "Verenigde Staten",
        hr: "Sjedinjene Američke Države",
        fa: "ایالات متحده آمریکا",
        de: "Vereinigte Staaten von Amerika",
        es: "Estados Unidos",
        fr: "États-Unis",
        ja: "アメリカ合衆国",
        it: "Stati Uniti D'America",
        hu: "Amerikai Egyesült Államok",
      },
      flag: "https://flagcdn.com/us.svg",
      regionalBlocs: [
        {
          acronym: "NAFTA",
          name: "North American Free Trade Agreement",
          otherNames: [
            "Tratado de Libre Comercio de América del Norte",
            "Accord de Libre-échange Nord-Américain",
          ],
        },
      ],
      cioc: "USA",
      independent: true,
    },
    {
      name: "Mexico",
      topLevelDomain: [".mx"],
      alpha2Code: "MX",
      alpha3Code: "MEX",
      callingCodes: ["52"],
      capital: "Mexico City",
      altSpellings: [
        "MX",
        "Mexicanos",
        "United Mexican States",
        "Estados Unidos Mexicanos",
      ],
      subregion: "North America",
      region: "Americas",
      population: 128932753,
      latlng: [23.0, -102.0],
      demonym: "Mexican",
      area: 1964375.0,
      gini: 45.4,
      timezones: ["UTC-08:00", "UTC-07:00", "UTC-06:00"],
      borders: ["BLZ", "GTM", "USA"],
      nativeName: "México",
      numericCode: "484",
      flags: {
        svg: "https://flagcdn.com/mx.svg",
        png: "https://flagcdn.com/w320/mx.png",
      },
      currencies: [{ code: "MXN", name: "Mexican peso", symbol: "$" }],
      languages: [
        {
          iso639_1: "es",
          iso639_2: "spa",
          name: "Spanish",
          nativeName: "Español",
        },
      ],
      translations: {
        br: "México",
        pt: "México",
        nl: "Mexico",
        hr: "Meksiko",
        fa: "مکزیک",
        de: "Mexiko",
        es: "México",
        fr: "Mexique",
        ja: "メキシコ",
        it: "Messico",
        hu: "Mexikó",
      },
      flag: "https://flagcdn.com/mx.svg",
      regionalBlocs: [
        {
          acronym: "PA",
          name: "Pacific Alliance",
          otherNames: ["Alianza del Pacífico"],
        },
        {
          acronym: "NAFTA",
          name: "North American Free Trade Agreement",
          otherNames: [
            "Tratado de Libre Comercio de América del Norte",
            "Accord de Libre-échange Nord-Américain",
          ],
        },
      ],
      cioc: "MEX",
      independent: true,
    },
  ],
  [
    {
      name: "Brazil",
      topLevelDomain: [".br"],
      alpha2Code: "BR",
      alpha3Code: "BRA",
      callingCodes: ["55"],
      capital: "Brasília",
      altSpellings: [
        "BR",
        "Brasil",
        "Federative Republic of Brazil",
        "República Federativa do Brasil",
      ],
      subregion: "South America",
      region: "Americas",
      population: 212559409,
      latlng: [-10.0, -55.0],
      demonym: "Brazilian",
      area: 8515767.0,
      gini: 53.4,
      timezones: ["UTC-05:00", "UTC-04:00", "UTC-03:00", "UTC-02:00"],
      borders: [
        "ARG",
        "BOL",
        "COL",
        "FRA",
        "GUF",
        "GUY",
        "PRY",
        "PER",
        "SUR",
        "URY",
        "VEN",
      ],
      nativeName: "Brasil",
      numericCode: "076",
      flags: {
        svg: "https://flagcdn.com/br.svg",
        png: "https://flagcdn.com/w320/br.png",
      },
      currencies: [{ code: "BRL", name: "Brazilian real", symbol: "R$" }],
      languages: [
        {
          iso639_1: "pt",
          iso639_2: "por",
          name: "Portuguese",
          nativeName: "Português",
        },
      ],
      translations: {
        br: "Brasil",
        pt: "Brasil",
        nl: "Brazilië",
        hr: "Brazil",
        fa: "برزیل",
        de: "Brasilien",
        es: "Brasil",
        fr: "Brésil",
        ja: "ブラジル",
        it: "Brasile",
        hu: "Brazília",
      },
      flag: "https://flagcdn.com/br.svg",
      regionalBlocs: [
        {
          acronym: "USAN",
          name: "Union of South American Nations",
          otherAcronyms: ["UNASUR", "UNASUL", "UZAN"],
          otherNames: [
            "Unión de Naciones Suramericanas",
            "União de Nações Sul-Americanas",
            "Unie van Zuid-Amerikaanse Naties",
            "South American Union",
          ],
        },
      ],
      cioc: "BRA",
      independent: true,
    },
  ],
  [
    {
      name: "Ukraine",
      topLevelDomain: [".ua"],
      alpha2Code: "UA",
      alpha3Code: "UKR",
      callingCodes: ["380"],
      capital: "Kyiv",
      altSpellings: ["UA", "Ukrayina"],
      subregion: "Eastern Europe",
      region: "Europe",
      population: 44134693,
      latlng: [49.0, 32.0],
      demonym: "Ukrainian",
      area: 603700.0,
      gini: 26.6,
      timezones: ["UTC+02:00"],
      borders: ["BLR", "HUN", "MDA", "POL", "ROU", "RUS", "SVK"],
      nativeName: "Україна",
      numericCode: "804",
      flags: {
        svg: "https://flagcdn.com/ua.svg",
        png: "https://flagcdn.com/w320/ua.png",
      },
      currencies: [{ code: "UAH", name: "Ukrainian hryvnia", symbol: "₴" }],
      languages: [
        {
          iso639_1: "uk",
          iso639_2: "ukr",
          name: "Ukrainian",
          nativeName: "Українська",
        },
      ],
      translations: {
        br: "Ucrânia",
        pt: "Ucrânia",
        nl: "Oekraïne",
        hr: "Ukrajina",
        fa: "وکراین",
        de: "Ukraine",
        es: "Ucrania",
        fr: "Ukraine",
        ja: "ウクライナ",
        it: "Ucraina",
        hu: "Ukrajna",
      },
      flag: "https://flagcdn.com/ua.svg",
      cioc: "UKR",
      independent: true,
    },
  ],
  [
    {
      name: "Russian Federation",
      topLevelDomain: [".ru"],
      alpha2Code: "RU",
      alpha3Code: "RUS",
      callingCodes: ["7"],
      capital: "Moscow",
      altSpellings: [
        "RU",
        "Rossiya",
        "Russian Federation",
        "Российская Федерация",
        "Rossiyskaya Federatsiya",
      ],
      subregion: "Eastern Europe",
      region: "Europe",
      population: 144104080,
      latlng: [60.0, 100.0],
      demonym: "Russian",
      area: 1.7124442e7,
      gini: 37.5,
      timezones: [
        "UTC+03:00",
        "UTC+04:00",
        "UTC+06:00",
        "UTC+07:00",
        "UTC+08:00",
        "UTC+09:00",
        "UTC+10:00",
        "UTC+11:00",
        "UTC+12:00",
      ],
      borders: [
        "AZE",
        "BLR",
        "CHN",
        "EST",
        "FIN",
        "GEO",
        "KAZ",
        "PRK",
        "LVA",
        "LTU",
        "MNG",
        "NOR",
        "POL",
        "UKR",
      ],
      nativeName: "Россия",
      numericCode: "643",
      flags: {
        svg: "https://flagcdn.com/ru.svg",
        png: "https://flagcdn.com/w320/ru.png",
      },
      currencies: [{ code: "RUB", name: "Russian ruble", symbol: "₽" }],
      languages: [
        {
          iso639_1: "ru",
          iso639_2: "rus",
          name: "Russian",
          nativeName: "Русский",
        },
      ],
      translations: {
        br: "Rússia",
        pt: "Rússia",
        nl: "Rusland",
        hr: "Rusija",
        fa: "روسیه",
        de: "Russland",
        es: "Rusia",
        fr: "Russie",
        ja: "ロシア連邦",
        it: "Russia",
        hu: "Oroszország",
      },
      flag: "https://flagcdn.com/ru.svg",
      regionalBlocs: [
        {
          acronym: "EEU",
          name: "Eurasian Economic Union",
          otherAcronyms: ["EAEU"],
        },
      ],
      cioc: "RUS",
      independent: true,
    },
  ],
  [
    {
      name: "Germany",
      capital: "Berlin",
      region: "Europe",
      population: 83240525,
      flags: {
        svg: "https://flagcdn.com/de.svg",
        png: "https://flagcdn.com/w320/de.png",
      },
      currencies: [{ code: "EUR", name: "Euro", symbol: "€" }],
      flag: "https://flagcdn.com/de.svg",
    },
  ],
  [
    {
      name: "United Kingdom of Great Britain and Northern Ireland",
      callingCodes: ["44"],
      capital: "London",
      region: "Europe",
      population: 67215293,
      flags: {
        svg: "https://flagcdn.com/gb.svg",
        png: "https://flagcdn.com/w320/gb.png",
      },
      currencies: [{ code: "GBP", name: "British pound", symbol: "£" }],
      flag: "https://flagcdn.com/gb.svg",
    },
  ],
  [
    {
      name: "Nigeria",
      capital: "Abuja",
      region: "Africa",
      population: 206139587,
      flags: {
        svg: "https://flagcdn.com/ng.svg",
        png: "https://flagcdn.com/w320/ng.png",
      },
      currencies: [{ code: "NGN", name: "Nigerian naira", symbol: "₦" }],
      languages: [
        {
          iso639_1: "en",
          iso639_2: "eng",
          name: "English",
          nativeName: "English",
        },
      ],
      flag: "https://flagcdn.com/ng.svg",
    },
  ],
  [
    {
      name: "Iceland",
      capital: "Reykjavík",
      region: "Europe",
      population: 366425,
      flags: {
        svg: "https://flagcdn.com/is.svg",
        png: "https://flagcdn.com/w320/is.png",
      },
      currencies: [{ code: "ISK", name: "Icelandic króna", symbol: "kr" }],
      languages: [
        {
          iso639_1: "is",
          iso639_2: "isl",
          name: "Icelandic",
          nativeName: "Íslenska",
        },
      ],
      flag: "https://flagcdn.com/is.svg",
    },
  ],
];
